VAGRANTFILE_API_VERSION ||= "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	vm_name = "bp_box"

	config.vm.box = "ubuntu/bionic64"
	config.vm.box_check_update = false
	config.vm.define "localhost"
	config.ssh.forward_agent = false

	config.vm.provider :virtualbox do |vb|
		vb.customize [ "modifyvm", :id, "--memory", 1024]
		vb.customize [ "modifyvm", :id, "--cpus", 1]
	end

        config.vm.network "forwarded_port", guest: 8080, host: 8080

	config.vm.network :private_network, ip: "192.168.10.10"

        config.vm.provision "shell", inline: "which python || sudo apt -y install python"

	[
		{ 'play' => "provision-run", 'tags' => [ "vagrant-configure" ] },
	].each do | run |
		config.vm.provision "ansible" do |ansible|
			ansible.compatibility_mode = '2.0'
			ansible.playbook = "#{run['play']}.yml"
			ansible.limit = "all,localhost"
			ansible.galaxy_role_file = "../ansible/requirements.yml"
                        ansible.galaxy_roles_path = "../ansible/roles"
                        #ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
		end
	end
end
