- name: Setting some static Hello World content
  template: 
    src: app-code.conf.j2 
    dest: "/vagrant/docker/app-code"

- name: Build app docker image
  docker_image:
     path: /vagrant/docker
     name: app

- name: Run Application
  docker_container:
    name: bp-app
    image: app
    state: started
    pull: no
    published_ports:
    - "8080:80"
